apiVersion: v1
kind: Secret
metadata:
  # The <release> component of the name must match the helm release name:
  # helm upgrade --install myreleasename ...
  # name: myreleasename-dsx-connect-api-auth-enrollment
  name: <release>-dsx-connect-api-auth-enrollment
  namespace: <namespace>
type: Opaque
stringData:
  ENROLLMENT_TOKEN: "change-me-strong-enrollment-token"
