site_name: DSX-Connect
site_description: Modular, scalable file scanning orchestration with pluggable connectors
repo_url: https://github.com/deep-instinct/dsx-connect
extra:
  social:
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://github.com/deep-instinct/dsx-connect
    - icon: fontawesome/brands/docker
      name: Docker Hub
      link: https://hub.docker.com/repositories/dsxconnect
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/dsx-connect-icon-white.svg
  favicon: assets/dsx-connect-icon-white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
    - header.social
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
#    - scheme: default
#      primary: teal
#      accent: amber
    - scheme: default
      primary: light blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started:
      - Overview: getting-started.md
      - Deploying the DSX-Connect Core: getting-started-core.md
      - Deploying Your First Connector: getting-started-connector.md
  - Connector Concepts: connectors/concepts.md
  - Deployment:
      - Overview: deployment/index.md
      - Docker:
          - Best Practices: deployment/docker/intro.md
          - DSX-Connect Core Deployment: deployment/docker/dsx-connect.md
          - Connector Deployments:
              - AWS S3: deployment/docker/aws-s3.md
              - Azure Blob Storage: deployment/docker/azure-blob.md
              - Filesystem: deployment/docker/filesystem.md
              - Google Cloud Storage: deployment/docker/google-cloud-storage.md
              - SharePoint: deployment/docker/sharepoint.md
              - Salesforce: deployment/docker/salesforce.md
              - M365 Email: deployment/docker/m365-mail.md
              - OneDrive: deployment/docker/onedrive.md
          - Deploying with SSL/TLS: deployment/docker/tls.md
      - Kubernetes:
          - Best Practices: deployment/kubernetes/getting-started.md
          - Quick Tutorial: deployment/kubernetes/getting-started-quickstart.md
          - DSX-Connect Core Deployment: deployment/kubernetes/dsx-connect.md
          - Connector Deployments:
              - AWS S3: deployment/kubernetes/aws-s3.md
              - Azure Blob Storage: deployment/kubernetes/azure-blob.md
              - Filesystem: deployment/kubernetes/filesystem.md
              - Google Cloud Storage: deployment/kubernetes/google-cloud-storage.md
              - SharePoint: deployment/kubernetes/sharepoint.md
              - Salesforce: deployment/kubernetes/salesforce.md
              - M365 Mail: deployment/kubernetes/m365-mail.md
              - OneDrive: deployment/kubernetes/onedrive.md
          - Using DSX-Connect Authentication: deployment/authentication.md
          - Deploying with SSL/TLS: deployment/tls.md
          - "Walkthrough: Deploying Full Stack with Authentication and TLS": deployment/kubernetes/getting-started-quickstart-azure.md
          - Advanced Connector Deployment: deployment/kubernetes/advanced-connector-deployment.md
          - Kubernetes Guides (Per Connector): deployment/k8s-guides.md
          - Log Collectors: deployment/log-collectors.md
      - Advanced Settings: deployment/advanced.md
  - Reference:
      - Assets: reference/assets.md
      - Azure Credentials: reference/azure-credentials.md
      - Google Cloud Credentials: reference/google-cloud-credentials.md
      - Advanced Kubernetes Network Security: reference/advanced-kubernetes-network-security.md
      - UI Display Icons: reference/display-icons.md
      - DSXA Python SDK: reference/dsxa-sdk.md
      - Filters (Details): reference/filters.md
  - Case Studies:
      - Scanning Windows Fileshares: case-studies/windows-fileshares.md
  - Developer's Guide:
      - Operations:
          - Connector State KV: operations/kv-state.md
  - Resources:
      - Docker Compose Bundles: https://github.com/deep-instinct/dsx-connect/releases
      - DSX-Connect Image Repo: https://hub.docker.com/repositories/dsxconnect
      - GitHub: https://github.com/deep-instinct/dsx-connect

plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - assets/docker-header.js
  - assets/termynal.js
extra_css:
  - assets/docker-header.css
  - assets/termynal.css
