apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsx-connect-api
  namespace: <namespace>
spec:
  ingressClassName: traefik
  rules:
    - host: <<dsx-connect.<ip address>.nip.io>>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsx-connect-api
                port:
                  number: 80
  tls:
    - hosts:
        - dsx-connect.<ip address>.nip.io
      secretName: <secret name>
